language: d

d:
  - dmd
  - ldc

before_install:
  - source ~/virtualenv/python3.6/bin/activate

install: pip install -r requirements.txt

script:
  - python gym_http_server.py &
  - rdmd --main -unittest -debug -g -version=gym_test gym.d
  - rdmd example.d
  - kill %1
